sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "lts/carbon"

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

branches:
  only:
    - master

script:
  - npm travis
